- name: Run Postgres
  docker_container:
    name: "{{ POSTGRES_CONTAINER }}" 
    image: primplouf/dockercourse-postgres:latest
    networks:
      - name: "{{ NETWORK }}" 
    env:
      POSTGRES_CONTAINER: "{{ POSTGRES_CONTAINER }}" 
      POSTGRES_DB: "{{ POSTGRES_DB }}" 
      POSTGRES_USER: "{{ POSTGRES_USER }}" 
      POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}" 
    volumes:
      - myvolume:/var/lib/postgresql/data
    recreate: true
    pull: true