- name: Run Front
  docker_container:
    name: front
    image: primplouf/dockercourse-frontend:latest  
    ports:
      - 80:80
    env:
      VUE_APP_API_URL: "{{ VUE_APP_API_URL }}"
    recreate: true
    pull: true